# Generated by Django 5.2 on 2025-04-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_description',
            field=models.CharField(max_length=211),
        ),
    ]
