# Generated by Django 5.2 on 2025-04-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_student_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_Education',
            field=models.CharField(max_length=40),
        ),
    ]
